homework Lesson2
Yesolo81/gbLessonsYesolo pull request #2
Opened 2021-08-01 18:40 UTC by Yesolo81

2021-08-02 11:00 UTC, mivafoxy commented on src/lesson2.java
> +    public static boolean longYear (int a){
Не хватает учета 100-ых годов.

2021-08-02 11:01 UTC, mivafoxy requested changes
Надо доделать задание с високосным годом

2021-08-02 16:54 UTC, Yesolo81 commented on src/lesson2.java
> +    public static boolean longYear (int a){
`return ((a%4 ==0 && a%100 != 0) || a%400 ==0)`
Согласен. Доработал.

2021-08-04 10:36 UTC, Yesolo81 commented
> Надо доделать задание с високосным годом

Fixed

2021-08-06 14:48 UTC, merged